"""Add fields to convidados

Revision ID: a7157c8e82f8
Revises: 4ddeaa5e5701
Create Date: 2021-01-17 23:16:05.781204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7157c8e82f8'
down_revision = '4ddeaa5e5701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convidados', sa.Column('negou_presenca', sa.Boolean(), nullable=True))
    op.add_column('convidados', sa.Column('pendencia', sa.Boolean(), nullable=True))
    op.add_column('convidados', sa.Column('pendencia_texto', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'convidados', 'categorias', ['fk_categoria'], ['id'])
    op.create_foreign_key(None, 'convidados', 'noivos', ['fk_noivo'], ['id'])
    op.create_foreign_key(None, 'presentes', 'categorias', ['fk_categoria'], ['id'])
    op.create_foreign_key(None, 'presentes_comprados', 'presentes', ['fk_presente'], ['id'])
    op.create_foreign_key(None, 'referencia_presentes', 'presentes', ['fk_presente'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referencia_presentes', type_='foreignkey')
    op.drop_constraint(None, 'presentes_comprados', type_='foreignkey')
    op.drop_constraint(None, 'presentes', type_='foreignkey')
    op.drop_constraint(None, 'convidados', type_='foreignkey')
    op.drop_constraint(None, 'convidados', type_='foreignkey')
    op.drop_column('convidados', 'pendencia_texto')
    op.drop_column('convidados', 'pendencia')
    op.drop_column('convidados', 'negou_presenca')
    # ### end Alembic commands ###
