"""add categorias

Revision ID: e8c62ccd186d
Revises: 255509338bcf
Create Date: 2020-08-28 12:19:19.322177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c62ccd186d'
down_revision = '255509338bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('convidados', sa.Column('fk_categoria', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'convidados', ['fk_categoria'])
    op.create_foreign_key(None, 'convidados', 'categorias', ['fk_categoria'], ['id'])
    op.create_foreign_key(None, 'convidados', 'noivos', ['fk_noivo'], ['id'])
    op.add_column('presentes', sa.Column('fk_categoria', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'presentes', ['fk_categoria'])
    op.create_foreign_key(None, 'presentes', 'categorias', ['fk_categoria'], ['id'])
    op.create_foreign_key(None, 'presentes_comprados', 'presentes', ['fk_presente'], ['id'])
    op.create_foreign_key(None, 'referencia_presentes', 'presentes', ['fk_presente'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referencia_presentes', type_='foreignkey')
    op.drop_constraint(None, 'presentes_comprados', type_='foreignkey')
    op.drop_constraint(None, 'presentes', type_='foreignkey')
    op.drop_constraint(None, 'presentes', type_='unique')
    op.drop_column('presentes', 'fk_categoria')
    op.drop_constraint(None, 'convidados', type_='foreignkey')
    op.drop_constraint(None, 'convidados', type_='foreignkey')
    op.drop_constraint(None, 'convidados', type_='unique')
    op.drop_column('convidados', 'fk_categoria')
    op.drop_table('categorias')
    # ### end Alembic commands ###
